#!/usr/bin/env bats

REPO_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"
SCRIPT="$REPO_DIR/scripts/cast-journal-build-mocs.sh"

setup() {
  set -euo pipefail

  # Create temp vault under BATS_TMPDIR
  VAULT_DIR="$BATS_TMPDIR/vault"
  mkdir -p "$VAULT_DIR"

  # Unset subprocess guard so tests can run the script
  export CLAUDE_SUBPROCESS=0
  export CAST_JOURNAL_VAULT="$VAULT_DIR"
}

teardown() {
  # Clean up temp vault
  rm -rf "$VAULT_DIR"
}

# ---------------------------------------------------------------------------
# Test 1: Script creates MOC for theme with 2 entries
# ---------------------------------------------------------------------------
@test "build-mocs: creates shared-theme.md with 2 entry links" {
  # Create temp vault structure with 3 entries
  mkdir -p "$VAULT_DIR/2026-05"

  # Entry 1: has shared-theme
  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [shared-theme]
---

# Entry 1

Some content here.
EOF

  # Entry 2: also has shared-theme
  cat > "$VAULT_DIR/2026-05/2026-05-02.md" <<'EOF'
---
themes: [shared-theme]
---

# Entry 2

Some content here.
EOF

  # Entry 3: has solo-theme
  cat > "$VAULT_DIR/2026-05/2026-05-03.md" <<'EOF'
---
themes: [solo-theme]
---

# Entry 3

Unique theme content.
EOF

  # Run the script
  run bash "$SCRIPT"

  [ "$status" -eq 0 ]

  # Verify Themes/shared-theme.md exists
  [ -f "$VAULT_DIR/Themes/shared-theme.md" ]

  # Check it contains both entry links
  CONTENT=$(cat "$VAULT_DIR/Themes/shared-theme.md")
  [[ "$CONTENT" == *"2026-05/2026-05-01.md"* ]]
  [[ "$CONTENT" == *"2026-05/2026-05-02.md"* ]]

  # Verify it doesn't contain solo-theme entry
  [[ "$CONTENT" != *"2026-05/2026-05-03.md"* ]]
}

# ---------------------------------------------------------------------------
# Test 2: Script creates MOC for solo theme with 1 entry
# ---------------------------------------------------------------------------
@test "build-mocs: creates solo-theme.md with 1 entry link" {
  mkdir -p "$VAULT_DIR/2026-05"

  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [shared-theme]
---

# Entry 1
Content.
EOF

  cat > "$VAULT_DIR/2026-05/2026-05-02.md" <<'EOF'
---
themes: [shared-theme]
---

# Entry 2
Content.
EOF

  cat > "$VAULT_DIR/2026-05/2026-05-03.md" <<'EOF'
---
themes: [solo-theme]
---

# Entry 3
Content.
EOF

  run bash "$SCRIPT"

  [ "$status" -eq 0 ]

  # Verify solo-theme MOC exists
  [ -f "$VAULT_DIR/Themes/solo-theme.md" ]

  # Check it contains exactly 1 entry link
  CONTENT=$(cat "$VAULT_DIR/Themes/solo-theme.md")
  [[ "$CONTENT" == *"2026-05/2026-05-03.md"* ]]

  # Verify it doesn't contain shared-theme entries
  [[ "$CONTENT" != *"2026-05/2026-05-01.md"* ]]
  [[ "$CONTENT" != *"2026-05/2026-05-02.md"* ]]
}

# ---------------------------------------------------------------------------
# Test 3: No modification of journal entry files (stat mtime unchanged)
# ---------------------------------------------------------------------------
@test "build-mocs: does not modify entry files (mtime preserved)" {
  mkdir -p "$VAULT_DIR/2026-05"

  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [test-theme]
---

# Entry 1
Content.
EOF

  # Get mtime before running script
  MTIME_BEFORE=$(stat -f %m "$VAULT_DIR/2026-05/2026-05-01.md" 2>/dev/null || stat -c %Y "$VAULT_DIR/2026-05/2026-05-01.md" 2>/dev/null)

  # Sleep to ensure time passes
  sleep 1

  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  # Get mtime after running script
  MTIME_AFTER=$(stat -f %m "$VAULT_DIR/2026-05/2026-05-01.md" 2>/dev/null || stat -c %Y "$VAULT_DIR/2026-05/2026-05-01.md" 2>/dev/null)

  # mtimes should be equal (file not modified)
  [ "$MTIME_BEFORE" -eq "$MTIME_AFTER" ]
}

# ---------------------------------------------------------------------------
# Test 4: Script is idempotent — running twice produces identical output
# ---------------------------------------------------------------------------
@test "build-mocs: idempotent — running twice produces identical files" {
  mkdir -p "$VAULT_DIR/2026-05"

  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [test-theme]
---

# Entry 1
Content.
EOF

  # Run script first time
  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  # Capture first output
  FIRST_OUTPUT=$(cat "$VAULT_DIR/Themes/test-theme.md")

  # Sleep a bit
  sleep 1

  # Run script second time
  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  # Capture second output
  SECOND_OUTPUT=$(cat "$VAULT_DIR/Themes/test-theme.md")

  # Remove disclaimer line (it may vary with date) for comparison
  FIRST_STRIPPED=$(echo "$FIRST_OUTPUT" | grep -v "Auto-generated by cast-journal-build-mocs.sh" || true)
  SECOND_STRIPPED=$(echo "$SECOND_OUTPUT" | grep -v "Auto-generated by cast-journal-build-mocs.sh" || true)

  [ "$FIRST_STRIPPED" = "$SECOND_STRIPPED" ]
}

# ---------------------------------------------------------------------------
# Test 5: Entries without themes frontmatter are silently ignored
# ---------------------------------------------------------------------------
@test "build-mocs: silently ignores entries without themes frontmatter" {
  mkdir -p "$VAULT_DIR/2026-05"

  # Entry with no frontmatter at all
  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
# Entry without frontmatter

Just some content.
EOF

  # Entry with frontmatter but no themes key
  cat > "$VAULT_DIR/2026-05/2026-05-02.md" <<'EOF'
---
author: Claude
---

# Entry with frontmatter but no themes

Some content.
EOF

  # Entry with valid themes
  cat > "$VAULT_DIR/2026-05/2026-05-03.md" <<'EOF'
---
themes: [valid-theme]
---

# Entry with themes

Content.
EOF

  run bash "$SCRIPT"

  [ "$status" -eq 0 ]

  # Only valid-theme.md should be created
  [ -f "$VAULT_DIR/Themes/valid-theme.md" ]
  [ ! -f "$VAULT_DIR/Themes/author.md" ]

  # Verify the valid MOC contains only the themed entry
  CONTENT=$(cat "$VAULT_DIR/Themes/valid-theme.md")
  [[ "$CONTENT" == *"2026-05/2026-05-03.md"* ]]
  [[ "$CONTENT" != *"2026-05/2026-05-01.md"* ]]
  [[ "$CONTENT" != *"2026-05/2026-05-02.md"* ]]
}

# ---------------------------------------------------------------------------
# Test 6: Multiple themes on single entry are parsed correctly
# ---------------------------------------------------------------------------
@test "build-mocs: parses multiple themes on single entry" {
  mkdir -p "$VAULT_DIR/2026-05"

  # Entry with multiple themes
  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [theme-a, theme-b, theme-c]
---

# Multi-theme entry

Content.
EOF

  run bash "$SCRIPT"

  [ "$status" -eq 0 ]

  # All three theme files should exist
  [ -f "$VAULT_DIR/Themes/theme-a.md" ]
  [ -f "$VAULT_DIR/Themes/theme-b.md" ]
  [ -f "$VAULT_DIR/Themes/theme-c.md" ]

  # Each should contain the same entry
  [[ $(cat "$VAULT_DIR/Themes/theme-a.md") == *"2026-05/2026-05-01.md"* ]]
  [[ $(cat "$VAULT_DIR/Themes/theme-b.md") == *"2026-05/2026-05-01.md"* ]]
  [[ $(cat "$VAULT_DIR/Themes/theme-c.md") == *"2026-05/2026-05-01.md"* ]]
}

# ---------------------------------------------------------------------------
# Test 7: MOC file format is correct (header, separator, section)
# ---------------------------------------------------------------------------
@test "build-mocs: MOC file has correct format" {
  mkdir -p "$VAULT_DIR/2026-05"

  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [format-test]
---

# Entry
Content.
EOF

  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  CONTENT=$(cat "$VAULT_DIR/Themes/format-test.md")

  # Must start with theme header
  [[ "$CONTENT" == "# Theme: format-test"* ]]

  # Must contain the new disclaimer text
  [[ "$CONTENT" == *"Replace this header with a hand-written description if you want"* ]]

  # Must have ## Entries section
  [[ "$CONTENT" == *"## Entries"* ]]

  # Must contain entry link in wiki format
  [[ "$CONTENT" == *"[[2026-05/2026-05-01.md]]"* ]]
}

# ---------------------------------------------------------------------------
# Test 8: Fresh MOC has marker fence
# ---------------------------------------------------------------------------
@test "build-mocs: fresh MOC contains marker fence with entries" {
  # Guard: ensure we're in BATS_TMPDIR
  [[ "$VAULT_DIR" == "$BATS_TMPDIR"/* ]] || { echo "refusing to use vault outside tmpdir: $VAULT_DIR" >&2; return 1; }

  mkdir -p "$VAULT_DIR/2026-05"

  # Create 2 entries with bravo theme
  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [bravo]
---

# Entry 1
Content.
EOF

  cat > "$VAULT_DIR/2026-05/2026-05-02.md" <<'EOF'
---
themes: [bravo]
---

# Entry 2
Content.
EOF

  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  # Verify Themes/bravo.md exists
  [ -f "$VAULT_DIR/Themes/bravo.md" ]

  CONTENT=$(cat "$VAULT_DIR/Themes/bravo.md")

  # Must contain both start and end markers
  [[ "$CONTENT" == *"<!-- CAST-JOURNAL-AUTO-ENTRIES-START -->"* ]]
  [[ "$CONTENT" == *"<!-- CAST-JOURNAL-AUTO-ENTRIES-END -->"* ]]

  # Must contain 2 bullet entries between markers
  [[ "$CONTENT" == *"- [[2026-05/2026-05-01.md]]"* ]]
  [[ "$CONTENT" == *"- [[2026-05/2026-05-02.md]]"* ]]
}

# ---------------------------------------------------------------------------
# Test 9: In-place replace preserves hand-curated content
# ---------------------------------------------------------------------------
@test "build-mocs: hand-curated content preserved outside markers" {
  # Guard: ensure we're in BATS_TMPDIR
  [[ "$VAULT_DIR" == "$BATS_TMPDIR"/* ]] || { echo "refusing to use vault outside tmpdir: $VAULT_DIR" >&2; return 1; }

  mkdir -p "$VAULT_DIR/2026-05"
  mkdir -p "$VAULT_DIR/Themes"

  # Pre-create Themes/alpha.md with hand-curated description
  cat > "$VAULT_DIR/Themes/alpha.md" <<'EOF'
# Theme: Alpha

This is a hand-written description
that spans multiple lines
and should be preserved
when we update the entries
by the auto-builder.

## Entries

<!-- CAST-JOURNAL-AUTO-ENTRIES-START -->
- [[2099-12-31/2099-12-31.md]]
<!-- CAST-JOURNAL-AUTO-ENTRIES-END -->
EOF

  # Capture the hand-curated part before running script
  CURATED_BEFORE=$(head -8 "$VAULT_DIR/Themes/alpha.md")

  # Create 2 real entries with alpha theme
  cat > "$VAULT_DIR/2026-05/2026-05-10.md" <<'EOF'
---
themes: [alpha]
---

# Entry A
Content.
EOF

  cat > "$VAULT_DIR/2026-05/2026-05-11.md" <<'EOF'
---
themes: [alpha]
---

# Entry B
Content.
EOF

  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  CONTENT=$(cat "$VAULT_DIR/Themes/alpha.md")

  # Verify the hand-curated part is byte-identical
  CURATED_AFTER=$(head -8 "$VAULT_DIR/Themes/alpha.md")
  [ "$CURATED_BEFORE" = "$CURATED_AFTER" ]

  # Verify the bullet list now references the real entries
  [[ "$CONTENT" == *"- [[2026-05/2026-05-10.md]]"* ]]
  [[ "$CONTENT" == *"- [[2026-05/2026-05-11.md]]"* ]]

  # Verify the stale entry is gone
  [[ "$CONTENT" != *"2099-12-31"* ]]
}

# ---------------------------------------------------------------------------
# Test 10: Markerless MOC gets migration block appended
# ---------------------------------------------------------------------------
@test "build-mocs: markerless MOC gets migration section appended" {
  # Guard: ensure we're in BATS_TMPDIR
  [[ "$VAULT_DIR" == "$BATS_TMPDIR"/* ]] || { echo "refusing to use vault outside tmpdir: $VAULT_DIR" >&2; return 1; }

  mkdir -p "$VAULT_DIR/2026-05"
  mkdir -p "$VAULT_DIR/Themes"

  # Pre-create Themes/charlie.md with 20 lines of hand-curated content, no markers
  cat > "$VAULT_DIR/Themes/charlie.md" <<'EOF'
# Theme: Charlie

This is a longer hand-curated description
that contains multiple paragraphs
and various content types.

Some details about the theme.
More details here.
And more.
And more.
Line 9
Line 10
Line 11
Line 12
Line 13
Line 14
Line 15
Line 16
Line 17
Line 18
Line 19
Line 20
EOF

  # Capture line count before
  LINE_COUNT_BEFORE=$(wc -l < "$VAULT_DIR/Themes/charlie.md")

  # Create 1 entry with charlie theme
  cat > "$VAULT_DIR/2026-05/2026-05-20.md" <<'EOF'
---
themes: [charlie]
---

# Entry Charlie
Content.
EOF

  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  CONTENT=$(cat "$VAULT_DIR/Themes/charlie.md")

  # Verify the first 20 lines are byte-identical
  ORIGINAL_PART=$(head -20 "$VAULT_DIR/Themes/charlie.md")
  # Re-read the original fixture to ensure we have it intact
  FIXTURE_LINES=20
  [[ $(echo "$ORIGINAL_PART" | wc -l) -eq $FIXTURE_LINES ]]

  # Verify the file now has more lines (migration section added)
  LINE_COUNT_AFTER=$(wc -l < "$VAULT_DIR/Themes/charlie.md")
  [ "$LINE_COUNT_AFTER" -gt "$LINE_COUNT_BEFORE" ]

  # Verify the migration section is at the end
  [[ "$CONTENT" == *"## Auto-indexed entries"* ]]
  [[ "$CONTENT" == *"<!-- CAST-JOURNAL-AUTO-ENTRIES-START -->"* ]]
  [[ "$CONTENT" == *"<!-- CAST-JOURNAL-AUTO-ENTRIES-END -->"* ]]

  # Verify the new entry is in the appended section
  [[ "$CONTENT" == *"- [[2026-05/2026-05-20.md]]"* ]]

  # Verify the last line is the end marker
  LAST_LINE=$(tail -1 "$VAULT_DIR/Themes/charlie.md")
  [[ "$LAST_LINE" == "<!-- CAST-JOURNAL-AUTO-ENTRIES-END -->"* ]]
}

# ---------------------------------------------------------------------------
# Test 11: Idempotency — Case 3 file becomes Case 2 on second run
# ---------------------------------------------------------------------------
@test "build-mocs: idempotent append — second run doesn't duplicate migration block" {
  # Guard: ensure we're in BATS_TMPDIR
  [[ "$VAULT_DIR" == "$BATS_TMPDIR"/* ]] || { echo "refusing to use vault outside tmpdir: $VAULT_DIR" >&2; return 1; }

  mkdir -p "$VAULT_DIR/2026-05"
  mkdir -p "$VAULT_DIR/Themes"

  # Pre-create Themes/delta.md with hand-curated content, no markers
  cat > "$VAULT_DIR/Themes/delta.md" <<'EOF'
# Theme: Delta

Hand-written content.
More content.
EOF

  # Create 1 entry with delta theme
  cat > "$VAULT_DIR/2026-05/2026-05-30.md" <<'EOF'
---
themes: [delta]
---

# Entry Delta
Content.
EOF

  # Run script first time
  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  # Capture output after first run
  FIRST_OUTPUT=$(cat "$VAULT_DIR/Themes/delta.md")
  FIRST_SIZE=$(wc -c < "$VAULT_DIR/Themes/delta.md")

  # Sleep to ensure time passes
  sleep 1

  # Run script second time
  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  # Capture output after second run
  SECOND_OUTPUT=$(cat "$VAULT_DIR/Themes/delta.md")
  SECOND_SIZE=$(wc -c < "$VAULT_DIR/Themes/delta.md")

  # Files should be byte-identical
  [ "$FIRST_OUTPUT" = "$SECOND_OUTPUT" ]
  [ "$FIRST_SIZE" -eq "$SECOND_SIZE" ]

  # Verify markers are present (Case 2 behavior on second run)
  [[ "$SECOND_OUTPUT" == *"<!-- CAST-JOURNAL-AUTO-ENTRIES-START -->"* ]]
  [[ "$SECOND_OUTPUT" == *"<!-- CAST-JOURNAL-AUTO-ENTRIES-END -->"* ]]

  # Verify the entry is still referenced
  [[ "$SECOND_OUTPUT" == *"- [[2026-05/2026-05-30.md]]"* ]]
}
