#!/usr/bin/env bats

REPO_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"
SCRIPT="$REPO_DIR/scripts/cast-journal-build-mocs.sh"

setup() {
  set -euo pipefail

  # Create temp vault under BATS_TMPDIR
  VAULT_DIR="$BATS_TMPDIR/vault"
  mkdir -p "$VAULT_DIR"

  # Unset subprocess guard so tests can run the script
  export CLAUDE_SUBPROCESS=0
  export CAST_JOURNAL_VAULT="$VAULT_DIR"
}

teardown() {
  # Clean up temp vault
  rm -rf "$VAULT_DIR"
}

# ---------------------------------------------------------------------------
# Test 1: Script creates MOC for theme with 2 entries
# ---------------------------------------------------------------------------
@test "build-mocs: creates shared-theme.md with 2 entry links" {
  # Create temp vault structure with 3 entries
  mkdir -p "$VAULT_DIR/2026-05"

  # Entry 1: has shared-theme
  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [shared-theme]
---

# Entry 1

Some content here.
EOF

  # Entry 2: also has shared-theme
  cat > "$VAULT_DIR/2026-05/2026-05-02.md" <<'EOF'
---
themes: [shared-theme]
---

# Entry 2

Some content here.
EOF

  # Entry 3: has solo-theme
  cat > "$VAULT_DIR/2026-05/2026-05-03.md" <<'EOF'
---
themes: [solo-theme]
---

# Entry 3

Unique theme content.
EOF

  # Run the script
  run bash "$SCRIPT"

  [ "$status" -eq 0 ]

  # Verify Themes/shared-theme.md exists
  [ -f "$VAULT_DIR/Themes/shared-theme.md" ]

  # Check it contains both entry links
  CONTENT=$(cat "$VAULT_DIR/Themes/shared-theme.md")
  [[ "$CONTENT" == *"2026-05/2026-05-01.md"* ]]
  [[ "$CONTENT" == *"2026-05/2026-05-02.md"* ]]

  # Verify it doesn't contain solo-theme entry
  [[ "$CONTENT" != *"2026-05/2026-05-03.md"* ]]
}

# ---------------------------------------------------------------------------
# Test 2: Script creates MOC for solo theme with 1 entry
# ---------------------------------------------------------------------------
@test "build-mocs: creates solo-theme.md with 1 entry link" {
  mkdir -p "$VAULT_DIR/2026-05"

  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [shared-theme]
---

# Entry 1
Content.
EOF

  cat > "$VAULT_DIR/2026-05/2026-05-02.md" <<'EOF'
---
themes: [shared-theme]
---

# Entry 2
Content.
EOF

  cat > "$VAULT_DIR/2026-05/2026-05-03.md" <<'EOF'
---
themes: [solo-theme]
---

# Entry 3
Content.
EOF

  run bash "$SCRIPT"

  [ "$status" -eq 0 ]

  # Verify solo-theme MOC exists
  [ -f "$VAULT_DIR/Themes/solo-theme.md" ]

  # Check it contains exactly 1 entry link
  CONTENT=$(cat "$VAULT_DIR/Themes/solo-theme.md")
  [[ "$CONTENT" == *"2026-05/2026-05-03.md"* ]]

  # Verify it doesn't contain shared-theme entries
  [[ "$CONTENT" != *"2026-05/2026-05-01.md"* ]]
  [[ "$CONTENT" != *"2026-05/2026-05-02.md"* ]]
}

# ---------------------------------------------------------------------------
# Test 3: No modification of journal entry files (stat mtime unchanged)
# ---------------------------------------------------------------------------
@test "build-mocs: does not modify entry files (mtime preserved)" {
  mkdir -p "$VAULT_DIR/2026-05"

  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [test-theme]
---

# Entry 1
Content.
EOF

  # Get mtime before running script
  MTIME_BEFORE=$(stat -f %m "$VAULT_DIR/2026-05/2026-05-01.md" 2>/dev/null || stat -c %Y "$VAULT_DIR/2026-05/2026-05-01.md" 2>/dev/null)

  # Sleep to ensure time passes
  sleep 1

  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  # Get mtime after running script
  MTIME_AFTER=$(stat -f %m "$VAULT_DIR/2026-05/2026-05-01.md" 2>/dev/null || stat -c %Y "$VAULT_DIR/2026-05/2026-05-01.md" 2>/dev/null)

  # mtimes should be equal (file not modified)
  [ "$MTIME_BEFORE" -eq "$MTIME_AFTER" ]
}

# ---------------------------------------------------------------------------
# Test 4: Script is idempotent — running twice produces identical output
# ---------------------------------------------------------------------------
@test "build-mocs: idempotent — running twice produces identical files" {
  mkdir -p "$VAULT_DIR/2026-05"

  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [test-theme]
---

# Entry 1
Content.
EOF

  # Run script first time
  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  # Capture first output
  FIRST_OUTPUT=$(cat "$VAULT_DIR/Themes/test-theme.md")

  # Sleep a bit
  sleep 1

  # Run script second time
  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  # Capture second output
  SECOND_OUTPUT=$(cat "$VAULT_DIR/Themes/test-theme.md")

  # Remove date line for comparison (it will differ)
  FIRST_STRIPPED=$(echo "$FIRST_OUTPUT" | grep -v "Auto-generated by cast-journal-build-mocs.sh" | grep -v "^---$" || true)
  SECOND_STRIPPED=$(echo "$SECOND_OUTPUT" | grep -v "Auto-generated by cast-journal-build-mocs.sh" | grep -v "^---$" || true)

  [ "$FIRST_STRIPPED" = "$SECOND_STRIPPED" ]
}

# ---------------------------------------------------------------------------
# Test 5: Entries without themes frontmatter are silently ignored
# ---------------------------------------------------------------------------
@test "build-mocs: silently ignores entries without themes frontmatter" {
  mkdir -p "$VAULT_DIR/2026-05"

  # Entry with no frontmatter at all
  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
# Entry without frontmatter

Just some content.
EOF

  # Entry with frontmatter but no themes key
  cat > "$VAULT_DIR/2026-05/2026-05-02.md" <<'EOF'
---
author: Claude
---

# Entry with frontmatter but no themes

Some content.
EOF

  # Entry with valid themes
  cat > "$VAULT_DIR/2026-05/2026-05-03.md" <<'EOF'
---
themes: [valid-theme]
---

# Entry with themes

Content.
EOF

  run bash "$SCRIPT"

  [ "$status" -eq 0 ]

  # Only valid-theme.md should be created
  [ -f "$VAULT_DIR/Themes/valid-theme.md" ]
  [ ! -f "$VAULT_DIR/Themes/author.md" ]

  # Verify the valid MOC contains only the themed entry
  CONTENT=$(cat "$VAULT_DIR/Themes/valid-theme.md")
  [[ "$CONTENT" == *"2026-05/2026-05-03.md"* ]]
  [[ "$CONTENT" != *"2026-05/2026-05-01.md"* ]]
  [[ "$CONTENT" != *"2026-05/2026-05-02.md"* ]]
}

# ---------------------------------------------------------------------------
# Test 6: Multiple themes on single entry are parsed correctly
# ---------------------------------------------------------------------------
@test "build-mocs: parses multiple themes on single entry" {
  mkdir -p "$VAULT_DIR/2026-05"

  # Entry with multiple themes
  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [theme-a, theme-b, theme-c]
---

# Multi-theme entry

Content.
EOF

  run bash "$SCRIPT"

  [ "$status" -eq 0 ]

  # All three theme files should exist
  [ -f "$VAULT_DIR/Themes/theme-a.md" ]
  [ -f "$VAULT_DIR/Themes/theme-b.md" ]
  [ -f "$VAULT_DIR/Themes/theme-c.md" ]

  # Each should contain the same entry
  [[ $(cat "$VAULT_DIR/Themes/theme-a.md") == *"2026-05/2026-05-01.md"* ]]
  [[ $(cat "$VAULT_DIR/Themes/theme-b.md") == *"2026-05/2026-05-01.md"* ]]
  [[ $(cat "$VAULT_DIR/Themes/theme-c.md") == *"2026-05/2026-05-01.md"* ]]
}

# ---------------------------------------------------------------------------
# Test 7: MOC file format is correct (header, separator, section)
# ---------------------------------------------------------------------------
@test "build-mocs: MOC file has correct format" {
  mkdir -p "$VAULT_DIR/2026-05"

  cat > "$VAULT_DIR/2026-05/2026-05-01.md" <<'EOF'
---
themes: [format-test]
---

# Entry
Content.
EOF

  run bash "$SCRIPT"
  [ "$status" -eq 0 ]

  CONTENT=$(cat "$VAULT_DIR/Themes/format-test.md")

  # Must start with theme header
  [[ "$CONTENT" == "# Theme: format-test"* ]]

  # Must contain "Auto-generated by" line
  [[ "$CONTENT" == *"Auto-generated by cast-journal-build-mocs.sh"* ]]

  # Must have ## Entries section
  [[ "$CONTENT" == *"## Entries"* ]]

  # Must contain entry link in wiki format
  [[ "$CONTENT" == *"[[2026-05/2026-05-01.md]]"* ]]
}
