#!/usr/bin/env bash
# cast-journal-build-mocs.sh — rebuild Themes/*.md MOC files from themes: frontmatter
# Safe to run repeatedly (idempotent — preserves hand-curated content outside marker fences).
# Does NOT modify journal entries.

if [ "${CLAUDE_SUBPROCESS:-0}" = "1" ]; then exit 0; fi
set -euo pipefail

VAULT="${CAST_JOURNAL_VAULT:-$HOME/Documents/Claude}"
THEMES_DIR="$VAULT/Themes"
START_MARK='<!-- CAST-JOURNAL-AUTO-ENTRIES-START -->'
END_MARK='<!-- CAST-JOURNAL-AUTO-ENTRIES-END -->'
mkdir -p "$THEMES_DIR"

# Use temp file to collect theme data
# Respect BATS_TMPDIR for test environments, fall back to TMPDIR or system temp
TEMP_DIR="${BATS_TMPDIR:-${TMPDIR:-/tmp}}"
TEMP_THEMES="${TEMP_DIR}/cast_journal_mocs_$$_$RANDOM"
trap 'rm -f "$TEMP_THEMES"' EXIT

find "$VAULT" -path "$VAULT/????-??/????-??-??.md" -type f 2>/dev/null | sort | while read -r entry_file; do
  in_frontmatter=0
  while IFS= read -r line; do
    if [[ "$line" == "---" && "$in_frontmatter" -eq 0 ]]; then
      in_frontmatter=1
      continue
    fi
    if [[ "$line" == "---" && "$in_frontmatter" -eq 1 ]]; then
      break
    fi
    if [[ "$in_frontmatter" -eq 1 && "$line" =~ ^themes:[[:space:]]*\[(.+)\] ]]; then
      theme_list="${BASH_REMATCH[1]}"
      # Parse comma-separated themes, strip whitespace and quotes
      IFS=',' read -ra themes <<< "$theme_list"
      for theme in "${themes[@]}"; do
        # Strip whitespace and quotes
        theme=$(printf '%s\n' "$theme" | sed "s/[[:space:]'\"]//g")
        [[ -z "$theme" ]] && continue
        rel_path="${entry_file#"$VAULT/"}"
        echo "$theme|$rel_path" >> "$TEMP_THEMES"
      done
    fi
  done < "$entry_file"
done

# Process collected themes and write MOC files
declare -A MOC_CONTENT
if [[ -f "$TEMP_THEMES" ]]; then
  while IFS='|' read -r theme rel_path; do
    [[ -z "$theme" ]] && continue
    if [[ -z "${MOC_CONTENT[$theme]:-}" ]]; then
      MOC_CONTENT["$theme"]="- [[$rel_path]]"
    else
      MOC_CONTENT["$theme"]="${MOC_CONTENT[$theme]}"$'\n'"- [[$rel_path]]"
    fi
  done < "$TEMP_THEMES"
fi

for theme in "${!MOC_CONTENT[@]}"; do
  moc_file="$THEMES_DIR/${theme}.md"
  entry_block="$START_MARK"$'\n'"${MOC_CONTENT[$theme]}"$'\n'"$END_MARK"

  if [[ ! -f "$moc_file" ]]; then
    # Case 1: fresh file
    {
      echo "# Theme: ${theme}"
      echo ""
      echo "Auto-generated by cast-journal-build-mocs.sh on $(date +%Y-%m-%d). Replace this header with a hand-written description if you want — the auto-builder only replaces content between the markers below."
      echo ""
      echo "## Entries"
      echo ""
      printf '%s\n' "$entry_block"
    } > "$moc_file"
  elif grep -q "$START_MARK" "$moc_file" && grep -q "$END_MARK" "$moc_file"; then
    # Case 2: in-place replace between markers
    python3 - "$moc_file" "$entry_block" <<'PYEOF'
import sys, re
moc_path, new_block = sys.argv[1], sys.argv[2]
with open(moc_path) as f: content = f.read()
pattern = re.compile(
    r'<!-- CAST-JOURNAL-AUTO-ENTRIES-START -->.*?<!-- CAST-JOURNAL-AUTO-ENTRIES-END -->',
    re.DOTALL
)
content = pattern.sub(new_block, content, count=1)
with open(moc_path, 'w') as f: f.write(content)
PYEOF
  else
    # Case 3: append migration block at end
    {
      echo ""
      echo "## Auto-indexed entries"
      echo ""
      printf '%s\n' "$entry_block"
    } >> "$moc_file"
  fi
done

theme_count="${#MOC_CONTENT[@]}"
echo "MOC rebuild complete: $theme_count theme(s) in $THEMES_DIR"
